### ISSUE TITLE
docs.html update to new docs structure

### ISSUE THREAD

**Issue by el00ruobuob** [monero-project/kovri-site#110]
The docs.html file is still coded to display the old docs structure of files.  
Doesn't it need an update @anonimal & @rehrar ?

**Comment by rehrar** [comment]
Docs file is no longer in the primary navigation. I try to leave these things in for a month or so just in case we need an easy revert (I don't know if that's good git practice or not. Probably not). You can access it from the website, and it doesn't build with Jekyll because I put it in the exclude section, so it won't build.

**Comment by el00ruobuob** [comment]
But navigation is still pointing to docs. So there is something I don't understand here.

**Comment by el00ruobuob** [comment]
I must be blind. Yml is pointing to user and dev guides only.

**Comment by el00ruobuob** [comment]
Close because of OP mental illness
